-- =============================================================
-- Tezza Lending Platform — Full Database Schema
-- Combines all Flyway migrations in order: V1 → V7 → V8 → V99
-- Run against a fresh PostgreSQL database:
--   psql -U tezza -d tezza_lending -f schema.sql
-- =============================================================


-- -------------------------------------------------------------
-- V1: PRODUCTS
-- -------------------------------------------------------------

CREATE TABLE LOAN_PRODUCTS (
    ID                UUID          NOT NULL DEFAULT gen_random_uuid(),
    NAME              VARCHAR(100)  NOT NULL,
    DESCRIPTION       TEXT,
    TENURE_VALUE      INTEGER       NOT NULL,
    TENURE_TYPE       VARCHAR(10)   NOT NULL CHECK (TENURE_TYPE IN ('DAYS', 'MONTHS')),
    MIN_AMOUNT        NUMERIC(19,2) NOT NULL,
    MAX_AMOUNT        NUMERIC(19,2) NOT NULL,
    GRACE_PERIOD_DAYS INTEGER       NOT NULL DEFAULT 0,
    ACTIVE            BOOLEAN       NOT NULL DEFAULT TRUE,
    CREATED_AT        TIMESTAMP     NOT NULL DEFAULT NOW(),
    UPDATED_AT        TIMESTAMP     NOT NULL DEFAULT NOW(),
    CREATED_BY        VARCHAR(100),
    UPDATED_BY        VARCHAR(100),
    CONSTRAINT PK_LOAN_PRODUCTS PRIMARY KEY (ID),
    CONSTRAINT UQ_LOAN_PRODUCTS_NAME UNIQUE (NAME),
    CONSTRAINT CHK_LP_AMOUNTS CHECK (MAX_AMOUNT >= MIN_AMOUNT),
    CONSTRAINT CHK_LP_TENURE CHECK (TENURE_VALUE > 0)
);

CREATE TABLE PRODUCT_FEES (
    ID               UUID          NOT NULL DEFAULT gen_random_uuid(),
    PRODUCT_ID       UUID          NOT NULL,
    FEE_TYPE         VARCHAR(20)   NOT NULL CHECK (FEE_TYPE IN ('SERVICE_FEE', 'DAILY_FEE', 'LATE_FEE')),
    CALCULATION_TYPE VARCHAR(10)   NOT NULL CHECK (CALCULATION_TYPE IN ('FIXED', 'PERCENTAGE')),
    AMOUNT           NUMERIC(19,2) NOT NULL CHECK (AMOUNT >= 0),
    DAYS_AFTER_DUE   INTEGER       NOT NULL DEFAULT 0,
    ACTIVE           BOOLEAN       NOT NULL DEFAULT TRUE,
    CREATED_AT       TIMESTAMP     NOT NULL DEFAULT NOW(),
    UPDATED_AT       TIMESTAMP     NOT NULL DEFAULT NOW(),
    CREATED_BY       VARCHAR(100),
    UPDATED_BY       VARCHAR(100),
    CONSTRAINT PK_PRODUCT_FEES PRIMARY KEY (ID),
    CONSTRAINT FK_PF_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES LOAN_PRODUCTS(ID)
);

CREATE INDEX IDX_PRODUCT_FEES_PRODUCT_ID ON PRODUCT_FEES(PRODUCT_ID);


-- -------------------------------------------------------------
-- V2: CUSTOMERS
-- -------------------------------------------------------------

CREATE TABLE CUSTOMERS (
    ID           UUID         NOT NULL DEFAULT gen_random_uuid(),
    FIRST_NAME   VARCHAR(100) NOT NULL,
    LAST_NAME    VARCHAR(100) NOT NULL,
    EMAIL        VARCHAR(150) NOT NULL,
    PHONE        VARCHAR(20),
    NATIONAL_ID  VARCHAR(50),
    STATUS       VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE'
                              CHECK (STATUS IN ('ACTIVE', 'SUSPENDED', 'BLACKLISTED')),
    CREATED_AT   TIMESTAMP    NOT NULL DEFAULT NOW(),
    UPDATED_AT   TIMESTAMP    NOT NULL DEFAULT NOW(),
    CREATED_BY   VARCHAR(100),
    UPDATED_BY   VARCHAR(100),
    CONSTRAINT PK_CUSTOMERS PRIMARY KEY (ID),
    CONSTRAINT UQ_CUSTOMERS_EMAIL UNIQUE (EMAIL)
);

CREATE UNIQUE INDEX UQ_CUSTOMERS_NATIONAL_ID ON CUSTOMERS(NATIONAL_ID) WHERE NATIONAL_ID IS NOT NULL;

CREATE TABLE CUSTOMER_LOAN_LIMITS (
    ID               UUID          NOT NULL DEFAULT gen_random_uuid(),
    CUSTOMER_ID      UUID          NOT NULL,
    MIN_LIMIT        NUMERIC(19,2) NOT NULL DEFAULT 0,
    MAX_LIMIT        NUMERIC(19,2) NOT NULL,
    CURRENT_LIMIT    NUMERIC(19,2) NOT NULL,
    CREDIT_SCORE     INTEGER       NOT NULL DEFAULT 0,
    LAST_REVIEWED_AT TIMESTAMP,
    CREATED_AT       TIMESTAMP     NOT NULL DEFAULT NOW(),
    UPDATED_AT       TIMESTAMP     NOT NULL DEFAULT NOW(),
    CREATED_BY       VARCHAR(100),
    UPDATED_BY       VARCHAR(100),
    CONSTRAINT PK_CUSTOMER_LOAN_LIMITS PRIMARY KEY (ID),
    CONSTRAINT FK_CLL_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID),
    CONSTRAINT UQ_CLL_CUSTOMER UNIQUE (CUSTOMER_ID),
    CONSTRAINT CHK_CLL_LIMITS CHECK (MAX_LIMIT >= MIN_LIMIT AND CURRENT_LIMIT >= 0)
);

CREATE INDEX IDX_CUSTOMER_LOAN_LIMITS_CUSTOMER_ID ON CUSTOMER_LOAN_LIMITS(CUSTOMER_ID);


-- -------------------------------------------------------------
-- V3: LOANS
-- -------------------------------------------------------------

CREATE TABLE LOANS (
    ID                    UUID          NOT NULL DEFAULT gen_random_uuid(),
    LOAN_NUMBER           VARCHAR(50)   NOT NULL,
    CUSTOMER_ID           UUID          NOT NULL,
    PRODUCT_ID            UUID          NOT NULL,
    PRINCIPAL_AMOUNT      NUMERIC(19,2) NOT NULL,
    DISBURSED_AMOUNT      NUMERIC(19,2),
    OUTSTANDING_BALANCE   NUMERIC(19,2) NOT NULL CHECK (OUTSTANDING_BALANCE >= 0),
    STATUS                VARCHAR(15)   NOT NULL DEFAULT 'OPEN'
                                        CHECK (STATUS IN ('OPEN', 'CLOSED', 'CANCELLED', 'OVERDUE', 'WRITTEN_OFF')),
    LOAN_TYPE             VARCHAR(15)   NOT NULL
                                        CHECK (LOAN_TYPE IN ('LUMP_SUM', 'INSTALLMENT')),
    BILLING_CYCLE_TYPE    VARCHAR(15)   NOT NULL DEFAULT 'INDIVIDUAL'
                                        CHECK (BILLING_CYCLE_TYPE IN ('INDIVIDUAL', 'CONSOLIDATED')),
    CONSOLIDATED_DUE_DATE DATE,
    DUE_DATE              DATE          NOT NULL,
    DISBURSED_AT          TIMESTAMP,
    CLOSED_AT             TIMESTAMP,
    CREATED_AT            TIMESTAMP     NOT NULL DEFAULT NOW(),
    UPDATED_AT            TIMESTAMP     NOT NULL DEFAULT NOW(),
    CREATED_BY            VARCHAR(100),
    UPDATED_BY            VARCHAR(100),
    CONSTRAINT PK_LOANS PRIMARY KEY (ID),
    CONSTRAINT UQ_LOANS_NUMBER UNIQUE (LOAN_NUMBER),
    CONSTRAINT FK_LOANS_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID),
    CONSTRAINT FK_LOANS_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES LOAN_PRODUCTS(ID)
);

CREATE INDEX IDX_LOANS_CUSTOMER_ID ON LOANS(CUSTOMER_ID);
CREATE INDEX IDX_LOANS_STATUS ON LOANS(STATUS);
CREATE INDEX IDX_LOANS_DUE_DATE ON LOANS(DUE_DATE);

CREATE TABLE LOAN_INSTALLMENTS (
    ID                 UUID          NOT NULL DEFAULT gen_random_uuid(),
    LOAN_ID            UUID          NOT NULL,
    INSTALLMENT_NUMBER INTEGER       NOT NULL,
    PRINCIPAL_AMOUNT   NUMERIC(19,2) NOT NULL,
    FEE_AMOUNT         NUMERIC(19,2) NOT NULL DEFAULT 0,
    TOTAL_AMOUNT       NUMERIC(19,2) NOT NULL,
    OUTSTANDING_AMOUNT NUMERIC(19,2) NOT NULL,
    DUE_DATE           DATE          NOT NULL,
    PAID_AT            TIMESTAMP,
    STATUS             VARCHAR(10)   NOT NULL DEFAULT 'PENDING'
                                     CHECK (STATUS IN ('PENDING', 'PAID', 'OVERDUE')),
    CREATED_AT         TIMESTAMP     NOT NULL DEFAULT NOW(),
    UPDATED_AT         TIMESTAMP     NOT NULL DEFAULT NOW(),
    CREATED_BY         VARCHAR(100),
    UPDATED_BY         VARCHAR(100),
    CONSTRAINT PK_LOAN_INSTALLMENTS PRIMARY KEY (ID),
    CONSTRAINT FK_LI_LOAN FOREIGN KEY (LOAN_ID) REFERENCES LOANS(ID),
    CONSTRAINT UQ_LI_LOAN_NUMBER UNIQUE (LOAN_ID, INSTALLMENT_NUMBER)
);

CREATE INDEX IDX_LOAN_INSTALLMENTS_LOAN_ID ON LOAN_INSTALLMENTS(LOAN_ID);
CREATE INDEX IDX_LOAN_INSTALLMENTS_STATUS ON LOAN_INSTALLMENTS(STATUS);


-- -------------------------------------------------------------
-- V4: REPAYMENTS
-- -------------------------------------------------------------

CREATE TABLE REPAYMENTS (
    ID           UUID          NOT NULL DEFAULT gen_random_uuid(),
    LOAN_ID      UUID          NOT NULL,
    AMOUNT       NUMERIC(19,2) NOT NULL CHECK (AMOUNT > 0),
    REFERENCE    VARCHAR(100)  NOT NULL,
    CHANNEL      VARCHAR(10)   NOT NULL CHECK (CHANNEL IN ('MPESA', 'BANK', 'CASH')),
    PROCESSED_AT TIMESTAMP     NOT NULL DEFAULT NOW(),
    CREATED_AT   TIMESTAMP     NOT NULL DEFAULT NOW(),
    UPDATED_AT   TIMESTAMP     NOT NULL DEFAULT NOW(),
    CREATED_BY   VARCHAR(100),
    UPDATED_BY   VARCHAR(100),
    CONSTRAINT PK_REPAYMENTS PRIMARY KEY (ID),
    CONSTRAINT UQ_REPAYMENTS_REFERENCE UNIQUE (REFERENCE),
    CONSTRAINT FK_REPAYMENTS_LOAN FOREIGN KEY (LOAN_ID) REFERENCES LOANS(ID)
);

CREATE INDEX IDX_REPAYMENTS_LOAN_ID ON REPAYMENTS(LOAN_ID);


-- -------------------------------------------------------------
-- V5: NOTIFICATIONS
-- -------------------------------------------------------------

CREATE TABLE NOTIFICATION_TEMPLATES (
    ID            UUID         NOT NULL DEFAULT gen_random_uuid(),
    EVENT_TYPE    VARCHAR(50)  NOT NULL
                               CHECK (EVENT_TYPE IN ('LOAN_CREATED','DUE_REMINDER','REPAYMENT_ACK','OVERDUE_NOTICE')),
    CHANNEL       VARCHAR(10)  NOT NULL CHECK (CHANNEL IN ('EMAIL', 'SMS', 'PUSH')),
    SUBJECT       VARCHAR(200),
    BODY_TEMPLATE TEXT         NOT NULL,
    ACTIVE        BOOLEAN      NOT NULL DEFAULT TRUE,
    CREATED_AT    TIMESTAMP    NOT NULL DEFAULT NOW(),
    UPDATED_AT    TIMESTAMP    NOT NULL DEFAULT NOW(),
    CREATED_BY    VARCHAR(100),
    UPDATED_BY    VARCHAR(100),
    CONSTRAINT PK_NOTIFICATION_TEMPLATES PRIMARY KEY (ID),
    CONSTRAINT UQ_NT_TYPE_CHANNEL UNIQUE (EVENT_TYPE, CHANNEL)
);

CREATE TABLE NOTIFICATION_RULES (
    ID               UUID        NOT NULL DEFAULT gen_random_uuid(),
    PRODUCT_ID       UUID,
    CUSTOMER_SEGMENT VARCHAR(50),
    EVENT_TYPE       VARCHAR(50) NOT NULL,
    CHANNEL          VARCHAR(10) NOT NULL CHECK (CHANNEL IN ('EMAIL', 'SMS', 'PUSH')),
    ENABLED          BOOLEAN     NOT NULL DEFAULT TRUE,
    PRIORITY         INTEGER     NOT NULL DEFAULT 0,
    DELAY_MINUTES    INTEGER     NOT NULL DEFAULT 0,
    CREATED_AT       TIMESTAMP   NOT NULL DEFAULT NOW(),
    UPDATED_AT       TIMESTAMP   NOT NULL DEFAULT NOW(),
    CREATED_BY       VARCHAR(100),
    UPDATED_BY       VARCHAR(100),
    CONSTRAINT PK_NOTIFICATION_RULES PRIMARY KEY (ID),
    CONSTRAINT FK_NR_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES LOAN_PRODUCTS(ID)
);

CREATE INDEX IDX_NOTIFICATION_RULES_EVENT_TYPE ON NOTIFICATION_RULES(EVENT_TYPE);

CREATE TABLE NOTIFICATION_LOGS (
    ID            UUID         NOT NULL DEFAULT gen_random_uuid(),
    CUSTOMER_ID   UUID         NOT NULL,
    EVENT_TYPE    VARCHAR(50)  NOT NULL,
    CHANNEL       VARCHAR(10)  NOT NULL,
    RECIPIENT     VARCHAR(200) NOT NULL,
    STATUS        VARCHAR(10)  NOT NULL DEFAULT 'PENDING'
                               CHECK (STATUS IN ('SENT', 'FAILED', 'PENDING')),
    ERROR_MESSAGE TEXT,
    SENT_AT       TIMESTAMP,
    CREATED_AT    TIMESTAMP    NOT NULL DEFAULT NOW(),
    UPDATED_AT    TIMESTAMP    NOT NULL DEFAULT NOW(),
    CREATED_BY    VARCHAR(100),
    UPDATED_BY    VARCHAR(100),
    CONSTRAINT PK_NOTIFICATION_LOGS PRIMARY KEY (ID),
    CONSTRAINT FK_NL_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID)
);

CREATE INDEX IDX_NOTIFICATION_LOGS_CUSTOMER_ID ON NOTIFICATION_LOGS(CUSTOMER_ID);


-- -------------------------------------------------------------
-- V6: OAUTH2 / AUTH TABLES
-- -------------------------------------------------------------

CREATE TABLE IF NOT EXISTS OAUTH2_REGISTERED_CLIENT (
    ID                            VARCHAR(100)  NOT NULL,
    CLIENT_ID                     VARCHAR(100)  NOT NULL,
    CLIENT_ID_ISSUED_AT           TIMESTAMP     DEFAULT NOW() NOT NULL,
    CLIENT_SECRET                 VARCHAR(200),
    CLIENT_SECRET_EXPIRES_AT      TIMESTAMP,
    CLIENT_NAME                   VARCHAR(200)  NOT NULL,
    CLIENT_AUTHENTICATION_METHODS VARCHAR(1000) NOT NULL,
    AUTHORIZATION_GRANT_TYPES     VARCHAR(1000) NOT NULL,
    REDIRECT_URIS                 VARCHAR(1000),
    POST_LOGOUT_REDIRECT_URIS     VARCHAR(1000),
    SCOPES                        VARCHAR(1000) NOT NULL,
    CLIENT_SETTINGS               VARCHAR(2000) NOT NULL,
    TOKEN_SETTINGS                VARCHAR(2000) NOT NULL,
    CONSTRAINT PK_OAUTH2_REGISTERED_CLIENT PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS OAUTH2_AUTHORIZATION (
    ID                            VARCHAR(100) NOT NULL,
    REGISTERED_CLIENT_ID          VARCHAR(100) NOT NULL,
    PRINCIPAL_NAME                VARCHAR(200) NOT NULL,
    AUTHORIZATION_GRANT_TYPE      VARCHAR(100) NOT NULL,
    AUTHORIZED_SCOPES             VARCHAR(1000),
    ATTRIBUTES                    TEXT,
    STATE                         VARCHAR(500),
    AUTHORIZATION_CODE_VALUE      TEXT,
    AUTHORIZATION_CODE_ISSUED_AT  TIMESTAMP,
    AUTHORIZATION_CODE_EXPIRES_AT TIMESTAMP,
    AUTHORIZATION_CODE_METADATA   TEXT,
    ACCESS_TOKEN_VALUE            TEXT,
    ACCESS_TOKEN_ISSUED_AT        TIMESTAMP,
    ACCESS_TOKEN_EXPIRES_AT       TIMESTAMP,
    ACCESS_TOKEN_METADATA         TEXT,
    ACCESS_TOKEN_TYPE             VARCHAR(100),
    ACCESS_TOKEN_SCOPES           VARCHAR(1000),
    OID_TOKEN_VALUE               TEXT,
    OID_TOKEN_ISSUED_AT           TIMESTAMP,
    OID_TOKEN_EXPIRES_AT          TIMESTAMP,
    OID_TOKEN_CLAIMS              TEXT,
    REFRESH_TOKEN_VALUE           TEXT,
    REFRESH_TOKEN_ISSUED_AT       TIMESTAMP,
    REFRESH_TOKEN_EXPIRES_AT      TIMESTAMP,
    REFRESH_TOKEN_METADATA        TEXT,
    USER_CODE_VALUE               TEXT,
    USER_CODE_ISSUED_AT           TIMESTAMP,
    USER_CODE_EXPIRES_AT          TIMESTAMP,
    DEVICE_CODE_VALUE             TEXT,
    DEVICE_CODE_ISSUED_AT         TIMESTAMP,
    DEVICE_CODE_EXPIRES_AT        TIMESTAMP,
    DEVICE_CODE_METADATA          TEXT,
    CONSTRAINT PK_OAUTH2_AUTHORIZATION PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS OAUTH2_AUTHORIZATION_CONSENT (
    REGISTERED_CLIENT_ID VARCHAR(100)  NOT NULL,
    PRINCIPAL_NAME       VARCHAR(200)  NOT NULL,
    AUTHORITIES          VARCHAR(1000) NOT NULL,
    CONSTRAINT PK_OAUTH2_AUTHORIZATION_CONSENT PRIMARY KEY (REGISTERED_CLIENT_ID, PRINCIPAL_NAME)
);


-- -------------------------------------------------------------
-- V7: STORED PROCEDURES
-- -------------------------------------------------------------

-- FIFO repayment allocation across installments
CREATE OR REPLACE PROCEDURE proc_allocate_repayment(
    p_loan_id        UUID,
    p_payment_amount NUMERIC(19,2)
)
LANGUAGE plpgsql AS $$
DECLARE
    rec         RECORD;
    v_remaining NUMERIC(19,2) := p_payment_amount;
    v_apply     NUMERIC(19,2);
BEGIN
    FOR rec IN
        SELECT ID, OUTSTANDING_AMOUNT
        FROM LOAN_INSTALLMENTS
        WHERE LOAN_ID = p_loan_id
          AND STATUS  = 'PENDING'
        ORDER BY DUE_DATE ASC
    LOOP
        EXIT WHEN v_remaining <= 0;
        IF v_remaining >= rec.OUTSTANDING_AMOUNT THEN
            v_apply := rec.OUTSTANDING_AMOUNT;
            UPDATE LOAN_INSTALLMENTS
            SET OUTSTANDING_AMOUNT = 0,
                STATUS             = 'PAID',
                PAID_AT            = NOW(),
                UPDATED_AT         = NOW()
            WHERE ID = rec.ID;
        ELSE
            v_apply := v_remaining;
            UPDATE LOAN_INSTALLMENTS
            SET OUTSTANDING_AMOUNT = OUTSTANDING_AMOUNT - v_apply,
                UPDATED_AT         = NOW()
            WHERE ID = rec.ID;
        END IF;
        v_remaining := v_remaining - v_apply;
    END LOOP;
END;
$$;

-- Auto-close loan when balance reaches zero
CREATE OR REPLACE PROCEDURE proc_close_loan_if_paid(
    p_loan_id UUID
)
LANGUAGE plpgsql AS $$
BEGIN
    UPDATE LOANS
    SET STATUS     = 'CLOSED',
        CLOSED_AT  = NOW(),
        UPDATED_AT = NOW()
    WHERE ID                  = p_loan_id
      AND OUTSTANDING_BALANCE = 0
      AND STATUS IN ('OPEN', 'OVERDUE');
END;
$$;

-- Apply late fee to outstanding balance
CREATE OR REPLACE PROCEDURE proc_apply_late_fee(
    p_loan_id    UUID,
    p_fee_amount NUMERIC(19,2)
)
LANGUAGE plpgsql AS $$
BEGIN
    UPDATE LOANS
    SET OUTSTANDING_BALANCE = OUTSTANDING_BALANCE + p_fee_amount,
        UPDATED_AT          = NOW()
    WHERE ID = p_loan_id
      AND p_fee_amount > 0;
END;
$$;

-- Apply daily accrual fee to outstanding balance
CREATE OR REPLACE PROCEDURE proc_apply_daily_fee(
    p_loan_id    UUID,
    p_fee_amount NUMERIC(19,2)
)
LANGUAGE plpgsql AS $$
BEGIN
    UPDATE LOANS
    SET OUTSTANDING_BALANCE = OUTSTANDING_BALANCE + p_fee_amount,
        UPDATED_AT          = NOW()
    WHERE ID = p_loan_id
      AND p_fee_amount > 0;
END;
$$;

-- Bulk transition OPEN past-due loans to OVERDUE; returns count
CREATE OR REPLACE PROCEDURE proc_run_overdue_sweep(
    OUT p_count INTEGER
)
LANGUAGE plpgsql AS $$
DECLARE
    v_today DATE := CURRENT_DATE;
BEGIN
    p_count := 0;

    UPDATE LOAN_INSTALLMENTS li
    SET STATUS     = 'OVERDUE',
        UPDATED_AT = NOW()
    FROM LOANS l
    WHERE li.LOAN_ID  = l.ID
      AND l.STATUS    = 'OPEN'
      AND l.DUE_DATE  < v_today
      AND li.STATUS   = 'PENDING'
      AND li.DUE_DATE < v_today;

    UPDATE LOANS
    SET STATUS     = 'OVERDUE',
        UPDATED_AT = NOW()
    WHERE STATUS   = 'OPEN'
      AND DUE_DATE < v_today;

    GET DIAGNOSTICS p_count = ROW_COUNT;
END;
$$;


-- -------------------------------------------------------------
-- V8: SPRING MODULITH EVENT PUBLICATION
-- -------------------------------------------------------------

CREATE TABLE IF NOT EXISTS EVENT_PUBLICATION (
    ID               UUID     NOT NULL,
    LISTENER_ID      TEXT     NOT NULL,
    EVENT_TYPE       TEXT     NOT NULL,
    SERIALIZED_EVENT TEXT     NOT NULL,
    PUBLICATION_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    COMPLETION_DATE  TIMESTAMP WITH TIME ZONE,
    CONSTRAINT PK_EVENT_PUBLICATION PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_EVENT_PUBLICATION_COMPLETION_DATE
    ON EVENT_PUBLICATION (COMPLETION_DATE);


-- -------------------------------------------------------------
-- V99: SEED DATA
-- -------------------------------------------------------------

INSERT INTO LOAN_PRODUCTS (ID, NAME, DESCRIPTION, TENURE_VALUE, TENURE_TYPE, MIN_AMOUNT, MAX_AMOUNT, GRACE_PERIOD_DAYS, ACTIVE)
VALUES
    ('a1000000-0000-0000-0000-000000000001', 'Personal Quick Loan', 'Short-term personal loan up to 30 days', 30, 'DAYS', 1000.00, 50000.00, 3, TRUE),
    ('a1000000-0000-0000-0000-000000000002', 'Business Term Loan', '12-month business financing', 12, 'MONTHS', 10000.00, 500000.00, 5, TRUE);

INSERT INTO PRODUCT_FEES (ID, PRODUCT_ID, FEE_TYPE, CALCULATION_TYPE, AMOUNT, DAYS_AFTER_DUE, ACTIVE)
VALUES
    ('b1000000-0000-0000-0000-000000000001', 'a1000000-0000-0000-0000-000000000001', 'SERVICE_FEE', 'PERCENTAGE', 5.00, 0, TRUE),
    ('b1000000-0000-0000-0000-000000000002', 'a1000000-0000-0000-0000-000000000001', 'LATE_FEE',    'FIXED',      500.00, 3, TRUE),
    ('b1000000-0000-0000-0000-000000000003', 'a1000000-0000-0000-0000-000000000002', 'SERVICE_FEE', 'PERCENTAGE', 3.00, 0, TRUE),
    ('b1000000-0000-0000-0000-000000000004', 'a1000000-0000-0000-0000-000000000002', 'DAILY_FEE',   'PERCENTAGE', 0.10, 0, TRUE),
    ('b1000000-0000-0000-0000-000000000005', 'a1000000-0000-0000-0000-000000000002', 'LATE_FEE',    'PERCENTAGE', 2.00, 5, TRUE);

INSERT INTO CUSTOMERS (ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, NATIONAL_ID, STATUS)
VALUES
    ('c1000000-0000-0000-0000-000000000001', 'Alice', 'Wanjiku', 'alice.wanjiku@example.com', '+254700000001', '12345678', 'ACTIVE'),
    ('c1000000-0000-0000-0000-000000000002', 'Brian', 'Omondi',  'brian.omondi@example.com',  '+254700000002', '23456789', 'ACTIVE'),
    ('c1000000-0000-0000-0000-000000000003', 'Carol', 'Njeri',   'carol.njeri@example.com',   '+254700000003', '34567890', 'ACTIVE');

INSERT INTO CUSTOMER_LOAN_LIMITS (ID, CUSTOMER_ID, MIN_LIMIT, MAX_LIMIT, CURRENT_LIMIT, CREDIT_SCORE, LAST_REVIEWED_AT)
VALUES
    ('d1000000-0000-0000-0000-000000000001', 'c1000000-0000-0000-0000-000000000001', 1000.00,  50000.00,  50000.00,  750, NOW()),
    ('d1000000-0000-0000-0000-000000000002', 'c1000000-0000-0000-0000-000000000002', 1000.00, 100000.00, 100000.00, 800, NOW()),
    ('d1000000-0000-0000-0000-000000000003', 'c1000000-0000-0000-0000-000000000003', 1000.00,  30000.00,  30000.00, 600, NOW());

INSERT INTO NOTIFICATION_TEMPLATES (ID, EVENT_TYPE, CHANNEL, SUBJECT, BODY_TEMPLATE, ACTIVE)
VALUES
    ('e1000000-0000-0000-0000-000000000001', 'LOAN_CREATED',   'EMAIL', 'Your Tezza Loan {{loanNumber}} Has Been Disbursed',
     'Dear {{customerName}},\n\nYour loan {{loanNumber}} of KES {{amount}} has been disbursed successfully.\nDue date: {{dueDate}}.\n\nTezza Lending', TRUE),
    ('e1000000-0000-0000-0000-000000000002', 'LOAN_CREATED',   'SMS',   NULL,
     'Tezza: Loan {{loanNumber}} of KES {{amount}} disbursed. Due {{dueDate}}.', TRUE),
    ('e1000000-0000-0000-0000-000000000003', 'DUE_REMINDER',   'EMAIL', 'Payment Reminder: Loan {{loanNumber}} Due in 3 Days',
     'Dear {{customerName}},\n\nYour loan {{loanNumber}} payment of KES {{amount}} is due on {{dueDate}}.\n\nTezza Lending', TRUE),
    ('e1000000-0000-0000-0000-000000000004', 'DUE_REMINDER',   'SMS',   NULL,
     'Tezza: Payment reminder - Loan {{loanNumber}} KES {{amount}} due {{dueDate}}.', TRUE),
    ('e1000000-0000-0000-0000-000000000005', 'REPAYMENT_ACK',  'EMAIL', 'Payment Received - Loan {{loanNumber}}',
     'Dear {{customerName}},\n\nWe received your payment of KES {{amount}} for loan {{loanNumber}}.\nOutstanding balance: KES {{balance}}.\n\nTezza Lending', TRUE),
    ('e1000000-0000-0000-0000-000000000006', 'REPAYMENT_ACK',  'SMS',   NULL,
     'Tezza: Payment KES {{amount}} received for loan {{loanNumber}}. Balance: KES {{balance}}.', TRUE),
    ('e1000000-0000-0000-0000-000000000007', 'OVERDUE_NOTICE', 'EMAIL', 'OVERDUE: Loan {{loanNumber}} Requires Immediate Attention',
     'Dear {{customerName}},\n\nYour loan {{loanNumber}} is now OVERDUE. Outstanding balance: KES {{amount}}.\nLate fees are accruing. Please pay immediately.\n\nTezza Lending', TRUE),
    ('e1000000-0000-0000-0000-000000000008', 'OVERDUE_NOTICE', 'SMS',   NULL,
     'Tezza URGENT: Loan {{loanNumber}} overdue. KES {{amount}} outstanding. Pay now.', TRUE);

INSERT INTO NOTIFICATION_RULES (ID, PRODUCT_ID, CUSTOMER_SEGMENT, EVENT_TYPE, CHANNEL, ENABLED, PRIORITY, DELAY_MINUTES)
VALUES
    ('f1000000-0000-0000-0000-000000000001', NULL, NULL, 'LOAN_CREATED',   'EMAIL', TRUE, 1, 0),
    ('f1000000-0000-0000-0000-000000000002', NULL, NULL, 'LOAN_CREATED',   'SMS',   TRUE, 2, 0),
    ('f1000000-0000-0000-0000-000000000003', NULL, NULL, 'DUE_REMINDER',   'EMAIL', TRUE, 1, 0),
    ('f1000000-0000-0000-0000-000000000004', NULL, NULL, 'DUE_REMINDER',   'SMS',   TRUE, 2, 0),
    ('f1000000-0000-0000-0000-000000000005', NULL, NULL, 'REPAYMENT_ACK',  'EMAIL', TRUE, 1, 0),
    ('f1000000-0000-0000-0000-000000000006', NULL, NULL, 'REPAYMENT_ACK',  'SMS',   TRUE, 2, 0),
    ('f1000000-0000-0000-0000-000000000007', NULL, NULL, 'OVERDUE_NOTICE', 'EMAIL', TRUE, 1, 0),
    ('f1000000-0000-0000-0000-000000000008', NULL, NULL, 'OVERDUE_NOTICE', 'SMS',   TRUE, 2, 0);
