CREATE TABLE LOAN_PRODUCTS (
    ID                UUID          NOT NULL DEFAULT gen_random_uuid(),
    NAME              VARCHAR(100)  NOT NULL,
    DESCRIPTION       TEXT,
    TENURE_VALUE      INTEGER       NOT NULL,
    TENURE_TYPE       VARCHAR(10)   NOT NULL CHECK (TENURE_TYPE IN ('DAYS', 'MONTHS')),
    MIN_AMOUNT        NUMERIC(19,2) NOT NULL,
    MAX_AMOUNT        NUMERIC(19,2) NOT NULL,
    GRACE_PERIOD_DAYS INTEGER       NOT NULL DEFAULT 0,
    ACTIVE            BOOLEAN       NOT NULL DEFAULT TRUE,
    CREATED_AT        TIMESTAMP     NOT NULL DEFAULT NOW(),
    UPDATED_AT        TIMESTAMP     NOT NULL DEFAULT NOW(),
    CREATED_BY        VARCHAR(100),
    UPDATED_BY        VARCHAR(100),
    CONSTRAINT PK_LOAN_PRODUCTS PRIMARY KEY (ID),
    CONSTRAINT CHK_LP_AMOUNTS CHECK (MAX_AMOUNT >= MIN_AMOUNT),
    CONSTRAINT CHK_LP_TENURE CHECK (TENURE_VALUE > 0)
);

CREATE TABLE PRODUCT_FEES (
    ID               UUID          NOT NULL DEFAULT gen_random_uuid(),
    PRODUCT_ID       UUID          NOT NULL,
    FEE_TYPE         VARCHAR(20)   NOT NULL CHECK (FEE_TYPE IN ('SERVICE_FEE', 'DAILY_FEE', 'LATE_FEE')),
    CALCULATION_TYPE VARCHAR(10)   NOT NULL CHECK (CALCULATION_TYPE IN ('FIXED', 'PERCENTAGE')),
    AMOUNT           NUMERIC(19,2) NOT NULL CHECK (AMOUNT >= 0),
    DAYS_AFTER_DUE   INTEGER       NOT NULL DEFAULT 0,
    ACTIVE           BOOLEAN       NOT NULL DEFAULT TRUE,
    CREATED_AT       TIMESTAMP     NOT NULL DEFAULT NOW(),
    UPDATED_AT       TIMESTAMP     NOT NULL DEFAULT NOW(),
    CREATED_BY       VARCHAR(100),
    UPDATED_BY       VARCHAR(100),
    CONSTRAINT PK_PRODUCT_FEES PRIMARY KEY (ID),
    CONSTRAINT FK_PF_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES LOAN_PRODUCTS(ID)
);

CREATE INDEX IDX_PRODUCT_FEES_PRODUCT_ID ON PRODUCT_FEES(PRODUCT_ID);
