CREATE TABLE CUSTOMERS (
    ID           UUID         NOT NULL DEFAULT gen_random_uuid(),
    FIRST_NAME   VARCHAR(100) NOT NULL,
    LAST_NAME    VARCHAR(100) NOT NULL,
    EMAIL        VARCHAR(150) NOT NULL,
    PHONE        VARCHAR(20),
    NATIONAL_ID  VARCHAR(50),
    STATUS       VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE'
                              CHECK (STATUS IN ('ACTIVE', 'SUSPENDED', 'BLACKLISTED')),
    CREATED_AT   TIMESTAMP    NOT NULL DEFAULT NOW(),
    UPDATED_AT   TIMESTAMP    NOT NULL DEFAULT NOW(),
    CREATED_BY   VARCHAR(100),
    UPDATED_BY   VARCHAR(100),
    CONSTRAINT PK_CUSTOMERS PRIMARY KEY (ID),
    CONSTRAINT UQ_CUSTOMERS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT UQ_CUSTOMERS_NATIONAL_ID UNIQUE (NATIONAL_ID)
);

CREATE TABLE CUSTOMER_LOAN_LIMITS (
    ID               UUID          NOT NULL DEFAULT gen_random_uuid(),
    CUSTOMER_ID      UUID          NOT NULL,
    MIN_LIMIT        NUMERIC(19,2) NOT NULL DEFAULT 0,
    MAX_LIMIT        NUMERIC(19,2) NOT NULL,
    CURRENT_LIMIT    NUMERIC(19,2) NOT NULL,
    CREDIT_SCORE     INTEGER       NOT NULL DEFAULT 0,
    LAST_REVIEWED_AT TIMESTAMP,
    CREATED_AT       TIMESTAMP     NOT NULL DEFAULT NOW(),
    UPDATED_AT       TIMESTAMP     NOT NULL DEFAULT NOW(),
    CREATED_BY       VARCHAR(100),
    UPDATED_BY       VARCHAR(100),
    CONSTRAINT PK_CUSTOMER_LOAN_LIMITS PRIMARY KEY (ID),
    CONSTRAINT FK_CLL_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID),
    CONSTRAINT UQ_CLL_CUSTOMER UNIQUE (CUSTOMER_ID),
    CONSTRAINT CHK_CLL_LIMITS CHECK (MAX_LIMIT >= MIN_LIMIT AND CURRENT_LIMIT >= 0)
);

CREATE INDEX IDX_CUSTOMER_LOAN_LIMITS_CUSTOMER_ID ON CUSTOMER_LOAN_LIMITS(CUSTOMER_ID);
