CREATE TABLE LOANS (
    ID                    UUID          NOT NULL DEFAULT gen_random_uuid(),
    LOAN_NUMBER           VARCHAR(50)   NOT NULL,
    CUSTOMER_ID           UUID          NOT NULL,
    PRODUCT_ID            UUID          NOT NULL,
    PRINCIPAL_AMOUNT      NUMERIC(19,2) NOT NULL,
    DISBURSED_AMOUNT      NUMERIC(19,2),
    OUTSTANDING_BALANCE   NUMERIC(19,2) NOT NULL CHECK (OUTSTANDING_BALANCE >= 0),
    STATUS                VARCHAR(15)   NOT NULL DEFAULT 'OPEN'
                                        CHECK (STATUS IN ('OPEN', 'CLOSED', 'CANCELLED', 'OVERDUE', 'WRITTEN_OFF')),
    LOAN_TYPE             VARCHAR(15)   NOT NULL
                                        CHECK (LOAN_TYPE IN ('LUMP_SUM', 'INSTALLMENT')),
    BILLING_CYCLE_TYPE    VARCHAR(15)   NOT NULL DEFAULT 'INDIVIDUAL'
                                        CHECK (BILLING_CYCLE_TYPE IN ('INDIVIDUAL', 'CONSOLIDATED')),
    CONSOLIDATED_DUE_DATE DATE,
    DUE_DATE              DATE          NOT NULL,
    DISBURSED_AT          TIMESTAMP,
    CLOSED_AT             TIMESTAMP,
    CREATED_AT            TIMESTAMP     NOT NULL DEFAULT NOW(),
    UPDATED_AT            TIMESTAMP     NOT NULL DEFAULT NOW(),
    CREATED_BY            VARCHAR(100),
    UPDATED_BY            VARCHAR(100),
    CONSTRAINT PK_LOANS PRIMARY KEY (ID),
    CONSTRAINT UQ_LOANS_NUMBER UNIQUE (LOAN_NUMBER),
    CONSTRAINT FK_LOANS_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID),
    CONSTRAINT FK_LOANS_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES LOAN_PRODUCTS(ID)
);

CREATE INDEX IDX_LOANS_CUSTOMER_ID ON LOANS(CUSTOMER_ID);
CREATE INDEX IDX_LOANS_STATUS ON LOANS(STATUS);
CREATE INDEX IDX_LOANS_DUE_DATE ON LOANS(DUE_DATE);

CREATE TABLE LOAN_INSTALLMENTS (
    ID                 UUID          NOT NULL DEFAULT gen_random_uuid(),
    LOAN_ID            UUID          NOT NULL,
    INSTALLMENT_NUMBER INTEGER       NOT NULL,
    PRINCIPAL_AMOUNT   NUMERIC(19,2) NOT NULL,
    FEE_AMOUNT         NUMERIC(19,2) NOT NULL DEFAULT 0,
    TOTAL_AMOUNT       NUMERIC(19,2) NOT NULL,
    OUTSTANDING_AMOUNT NUMERIC(19,2) NOT NULL,
    DUE_DATE           DATE          NOT NULL,
    PAID_AT            TIMESTAMP,
    STATUS             VARCHAR(10)   NOT NULL DEFAULT 'PENDING'
                                     CHECK (STATUS IN ('PENDING', 'PAID', 'OVERDUE')),
    CREATED_AT         TIMESTAMP     NOT NULL DEFAULT NOW(),
    UPDATED_AT         TIMESTAMP     NOT NULL DEFAULT NOW(),
    CREATED_BY         VARCHAR(100),
    UPDATED_BY         VARCHAR(100),
    CONSTRAINT PK_LOAN_INSTALLMENTS PRIMARY KEY (ID),
    CONSTRAINT FK_LI_LOAN FOREIGN KEY (LOAN_ID) REFERENCES LOANS(ID),
    CONSTRAINT UQ_LI_LOAN_NUMBER UNIQUE (LOAN_ID, INSTALLMENT_NUMBER)
);

CREATE INDEX IDX_LOAN_INSTALLMENTS_LOAN_ID ON LOAN_INSTALLMENTS(LOAN_ID);
CREATE INDEX IDX_LOAN_INSTALLMENTS_STATUS ON LOAN_INSTALLMENTS(STATUS);
