CREATE TABLE REPAYMENTS (
    ID           UUID          NOT NULL DEFAULT gen_random_uuid(),
    LOAN_ID      UUID          NOT NULL,
    AMOUNT       NUMERIC(19,2) NOT NULL CHECK (AMOUNT > 0),
    REFERENCE    VARCHAR(100)  NOT NULL,
    CHANNEL      VARCHAR(10)   NOT NULL CHECK (CHANNEL IN ('MPESA', 'BANK', 'CASH')),
    PROCESSED_AT TIMESTAMP     NOT NULL DEFAULT NOW(),
    CREATED_AT   TIMESTAMP     NOT NULL DEFAULT NOW(),
    UPDATED_AT   TIMESTAMP     NOT NULL DEFAULT NOW(),
    CREATED_BY   VARCHAR(100),
    UPDATED_BY   VARCHAR(100),
    CONSTRAINT PK_REPAYMENTS PRIMARY KEY (ID),
    CONSTRAINT UQ_REPAYMENTS_REFERENCE UNIQUE (REFERENCE),
    CONSTRAINT FK_REPAYMENTS_LOAN FOREIGN KEY (LOAN_ID) REFERENCES LOANS(ID)
);

CREATE INDEX IDX_REPAYMENTS_LOAN_ID ON REPAYMENTS(LOAN_ID);
