CREATE TABLE NOTIFICATION_TEMPLATES (
    ID            UUID         NOT NULL DEFAULT gen_random_uuid(),
    EVENT_TYPE    VARCHAR(50)  NOT NULL
                               CHECK (EVENT_TYPE IN ('LOAN_CREATED','DUE_REMINDER','REPAYMENT_ACK','OVERDUE_NOTICE')),
    CHANNEL       VARCHAR(10)  NOT NULL CHECK (CHANNEL IN ('EMAIL', 'SMS', 'PUSH')),
    SUBJECT       VARCHAR(200),
    BODY_TEMPLATE TEXT         NOT NULL,
    ACTIVE        BOOLEAN      NOT NULL DEFAULT TRUE,
    CREATED_AT    TIMESTAMP    NOT NULL DEFAULT NOW(),
    UPDATED_AT    TIMESTAMP    NOT NULL DEFAULT NOW(),
    CREATED_BY    VARCHAR(100),
    UPDATED_BY    VARCHAR(100),
    CONSTRAINT PK_NOTIFICATION_TEMPLATES PRIMARY KEY (ID),
    CONSTRAINT UQ_NT_TYPE_CHANNEL UNIQUE (EVENT_TYPE, CHANNEL)
);

CREATE TABLE NOTIFICATION_RULES (
    ID               UUID        NOT NULL DEFAULT gen_random_uuid(),
    PRODUCT_ID       UUID,
    CUSTOMER_SEGMENT VARCHAR(50),
    EVENT_TYPE       VARCHAR(50) NOT NULL,
    CHANNEL          VARCHAR(10) NOT NULL CHECK (CHANNEL IN ('EMAIL', 'SMS', 'PUSH')),
    ENABLED          BOOLEAN     NOT NULL DEFAULT TRUE,
    PRIORITY         INTEGER     NOT NULL DEFAULT 0,
    DELAY_MINUTES    INTEGER     NOT NULL DEFAULT 0,
    CREATED_AT       TIMESTAMP   NOT NULL DEFAULT NOW(),
    UPDATED_AT       TIMESTAMP   NOT NULL DEFAULT NOW(),
    CREATED_BY       VARCHAR(100),
    UPDATED_BY       VARCHAR(100),
    CONSTRAINT PK_NOTIFICATION_RULES PRIMARY KEY (ID),
    CONSTRAINT FK_NR_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES LOAN_PRODUCTS(ID)
);

CREATE INDEX IDX_NOTIFICATION_RULES_EVENT_TYPE ON NOTIFICATION_RULES(EVENT_TYPE);

CREATE TABLE NOTIFICATION_LOGS (
    ID            UUID         NOT NULL DEFAULT gen_random_uuid(),
    CUSTOMER_ID   UUID         NOT NULL,
    EVENT_TYPE    VARCHAR(50)  NOT NULL,
    CHANNEL       VARCHAR(10)  NOT NULL,
    RECIPIENT     VARCHAR(200) NOT NULL,
    STATUS        VARCHAR(10)  NOT NULL DEFAULT 'PENDING'
                               CHECK (STATUS IN ('SENT', 'FAILED', 'PENDING')),
    ERROR_MESSAGE TEXT,
    SENT_AT       TIMESTAMP,
    CREATED_AT    TIMESTAMP    NOT NULL DEFAULT NOW(),
    UPDATED_AT    TIMESTAMP    NOT NULL DEFAULT NOW(),
    CREATED_BY    VARCHAR(100),
    UPDATED_BY    VARCHAR(100),
    CONSTRAINT PK_NOTIFICATION_LOGS PRIMARY KEY (ID),
    CONSTRAINT FK_NL_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID)
);

CREATE INDEX IDX_NOTIFICATION_LOGS_CUSTOMER_ID ON NOTIFICATION_LOGS(CUSTOMER_ID);
