CREATE TABLE IF NOT EXISTS OAUTH2_REGISTERED_CLIENT (
    ID                            VARCHAR(100) NOT NULL,
    CLIENT_ID                     VARCHAR(100) NOT NULL,
    CLIENT_ID_ISSUED_AT           TIMESTAMP DEFAULT NOW() NOT NULL,
    CLIENT_SECRET                 VARCHAR(200),
    CLIENT_SECRET_EXPIRES_AT      TIMESTAMP,
    CLIENT_NAME                   VARCHAR(200) NOT NULL,
    CLIENT_AUTHENTICATION_METHODS VARCHAR(1000) NOT NULL,
    AUTHORIZATION_GRANT_TYPES     VARCHAR(1000) NOT NULL,
    REDIRECT_URIS                 VARCHAR(1000),
    POST_LOGOUT_REDIRECT_URIS     VARCHAR(1000),
    SCOPES                        VARCHAR(1000) NOT NULL,
    CLIENT_SETTINGS               VARCHAR(2000) NOT NULL,
    TOKEN_SETTINGS                VARCHAR(2000) NOT NULL,
    CONSTRAINT PK_OAUTH2_REGISTERED_CLIENT PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS OAUTH2_AUTHORIZATION (
    ID                            VARCHAR(100) NOT NULL,
    REGISTERED_CLIENT_ID          VARCHAR(100) NOT NULL,
    PRINCIPAL_NAME                VARCHAR(200) NOT NULL,
    AUTHORIZATION_GRANT_TYPE      VARCHAR(100) NOT NULL,
    AUTHORIZED_SCOPES             VARCHAR(1000),
    ATTRIBUTES                    TEXT,
    STATE                         VARCHAR(500),
    AUTHORIZATION_CODE_VALUE      TEXT,
    AUTHORIZATION_CODE_ISSUED_AT  TIMESTAMP,
    AUTHORIZATION_CODE_EXPIRES_AT TIMESTAMP,
    AUTHORIZATION_CODE_METADATA   TEXT,
    ACCESS_TOKEN_VALUE            TEXT,
    ACCESS_TOKEN_ISSUED_AT        TIMESTAMP,
    ACCESS_TOKEN_EXPIRES_AT       TIMESTAMP,
    ACCESS_TOKEN_METADATA         TEXT,
    ACCESS_TOKEN_TYPE             VARCHAR(100),
    ACCESS_TOKEN_SCOPES           VARCHAR(1000),
    OID_TOKEN_VALUE               TEXT,
    OID_TOKEN_ISSUED_AT           TIMESTAMP,
    OID_TOKEN_EXPIRES_AT          TIMESTAMP,
    OID_TOKEN_CLAIMS              TEXT,
    REFRESH_TOKEN_VALUE           TEXT,
    REFRESH_TOKEN_ISSUED_AT       TIMESTAMP,
    REFRESH_TOKEN_EXPIRES_AT      TIMESTAMP,
    REFRESH_TOKEN_METADATA        TEXT,
    USER_CODE_VALUE               TEXT,
    USER_CODE_ISSUED_AT           TIMESTAMP,
    USER_CODE_EXPIRES_AT          TIMESTAMP,
    DEVICE_CODE_VALUE             TEXT,
    DEVICE_CODE_ISSUED_AT         TIMESTAMP,
    DEVICE_CODE_EXPIRES_AT        TIMESTAMP,
    DEVICE_CODE_METADATA          TEXT,
    CONSTRAINT PK_OAUTH2_AUTHORIZATION PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS OAUTH2_AUTHORIZATION_CONSENT (
    REGISTERED_CLIENT_ID VARCHAR(100) NOT NULL,
    PRINCIPAL_NAME       VARCHAR(200) NOT NULL,
    AUTHORITIES          VARCHAR(1000) NOT NULL,
    CONSTRAINT PK_OAUTH2_AUTHORIZATION_CONSENT PRIMARY KEY (REGISTERED_CLIENT_ID, PRINCIPAL_NAME)
);
