-- SPRING MODULITH EVENT PUBLICATION REGISTRY TABLE
CREATE TABLE IF NOT EXISTS EVENT_PUBLICATION (
    ID               UUID         NOT NULL,
    LISTENER_ID      TEXT         NOT NULL,
    EVENT_TYPE       TEXT         NOT NULL,
    SERIALIZED_EVENT TEXT         NOT NULL,
    PUBLICATION_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    COMPLETION_DATE  TIMESTAMP WITH TIME ZONE,
    CONSTRAINT PK_EVENT_PUBLICATION PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_EVENT_PUBLICATION_COMPLETION_DATE
    ON EVENT_PUBLICATION (COMPLETION_DATE);
